[package]
name = "foto-winkel"
version = "0.1.0"
edition = "2021"
authors = ["Cas Brugman <casbrugman@hotmail.nl>"]

[dependencies]
bevy_egui = "0.17.1"
futures-lite = "1.12.0"
image = "0.24.5"
rfd = "0.10.0"
dotenvy = "0.15.6"
dyn-clone = "1.0.9"
rand = "0.8.5"

[dependencies.uuid]
version = "1.2.2"
features = ["v4"]

[dependencies.bevy]
version = "0.9.1"
default-features = false
features = [
    "bevy_asset",
    "bevy_winit",
    "render",
    "jpeg",
    "png",
    "x11",
]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
