[package]
name = "img-editor-bevy"
version = "0.1.0"
edition = "2021"
authors = ["Cas Brugman <casbrugman@hotmail.nl>"]

[dependencies]
bevy_egui = "0.16.0"
futures-lite = "1.12.0"
image = "0.24.3"
rfd = "0.10.0"

[dependencies.bevy]
version = "0.8.1"
default-features = false
features = [
    "bevy_asset",
    "bevy_winit",
    "render",
    "jpeg",
    "png",
    "x11",
]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
